spring:
  application:
    name: jbone-i-admin
  redis:
    host: 127.0.0.1
    port: 6379
    password: jbone
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    cache: false
    enabled: true


#服务
server:
  port: 7001

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

management:
  security:
    enabled: false

#Jbone配置
jbone:
  cas:
    #CAS服务地址
    casServerUrl: https://jbone-cas.majunwei.com:8443/cas
    #当前系统地址
    currentServerUrlPrefix: http://jbone-i-admin.majunwei.com:7001
    #过滤器地址,CAS认证通过后会回掉到jbone.cas.currentServerUrlPrefix/jbone.cas.casFilterUrlPattern
    casFilterUrlPattern: /cas
    #登录成功后的跳转路径，默认"/"
    successUrl: /
    #未授权的跳转路径，默认"/403"
    unauthorizedUrl: /403
    #客户端Session失效 freemarker:
                     #    enabled: false
                     #  jpa:
                     #    show-sql: true时间，默认30分钟
    clientSessionTimeout: 180000
    #权限过滤规则
    filterChainDefinition:
      /health: anon
      /archaius: anon
      /refresh: anon
      /configprops: anon
      /env/**: anon
      /service-registry/**: anon
      /auditevents: anon
      /pause: anon
      /dump: anon
      /loggers/**: anon
      /resume: anon
      /metrics/**: anon
      /channels: anon
      /beans: anon
      /mappings: anon
      /autoconfig: anon
      /trace: anon
      /hystrix.stream/**: anon
      /info: anon
      /restart: anon
      /heapdump: anon
      /features: anon
      /**: authc
  #当前系统名，在系统管理里面对应的名字
  sys:
    serverName: jbone-i-admin
    jdbc:
      url: jdbc:mysql://121.42.174.77:3306/jbone_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
      username: jbone_sys
      password: Jbone_sys_666
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 10
      initialSize: 2
      maxWait: 10000
  #系统管理Feign调用配置
  rpc.sysServer.feign:
    protocol: http
    name: jbone-sys-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.majunwei.com

